### ISSUE TITLE
Skins and shadow DOM

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#34]
Figure out which in which way we want to support themes. What is the recommended way to do it etc.

**Comment by hugurp** [comment]
The thing is, skins are tightly coupled with the radio4000-player DOM. if the DOM changes, no skin work.
Therefore, before introducing any skin other than the `default` skin, the DOM should be stable. So imo, we have to wait for that.
Also, if the DOM changes, and skin are dependant on it, it maybe means we have to increment the player version, otherwise we break people's code. 

I think it would be nice to have skins served as css files outside `radio4000` and `radio4000-player`.

What i mean is that every skins could be encapsuled in their own `css` file, served from somewhere we have control uppon, zb: css.r4.com, and users could save their skin there and assign them on the player as a property of it `<radio4000-player css="css.r4.com/my-style.css">`.

I know you want skins to have a winamp feeling; personally the appearance of a player comes after its usability and feature criteria.
As a developer for this project, I don't want to maintain skins each time I'm going to implement something new, trying to make this player as best as it can become.

**Comment by oskarrough** [comment]
Yea, I agree. I removed all references to skins in the master branch and we can continue this once we're stable.

Until then anyone can of course write CSS on their end and skin to their hearts desire :) but we do not *officially* support it.

**Comment by hugurp** [comment]
cool! totally agree

**Comment by oskarrough** [comment]
So, the player will looked very wrong on most pages since it'll inherit styles like any other element. This is not what you'd expect when you're used to YouTube/Soundcloud embeds etc.

Let's enable `shadow DOM` as the default for now? @hugurp 

Later we can figure out how to make it an option so people can disable shadow DOM and style it, if they like.

**Comment by hugurp** [comment]
yes

**Comment by oskarrough** [comment]
Since we now have an iframe-version we don't need to use shadow dom for the web component version yet.
