### ISSUE TITLE
Error while loading channel with no image

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player#78]
![deepinscreenshot_select-area_20170901185737](https://user-images.githubusercontent.com/1502484/29979878-8b01a04a-8f47-11e7-9be4-9d7729e6711b.png)

**Comment by oskarrough** [comment]
hmm. Here it shows the error as it should: https://api.radio4000.com/iframe?slug=grataeng from this line https://github.com/internet4000/radio4000-player/blob/master/src/utils/store.js#L54.

But that also means `store.findChannelImage` either returns an error or a succesful promise. Since no image still technically returns a sucessful promise we should instead check that and return either a promise that resolves or rejects?

**Comment by oskarrough** [comment]
Fixed in https://github.com/internet4000/radio4000-player/commit/e8e93f899641a9b3bb70a47711a649645403756a
